version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    user: 1000:1000
    tty: true
    stdin_open: true
